### ISSUE TITLE
Add alias for bugfix and hotfix branches

### ISSUE THREAD

**Issue by Doug-Murphy** [ZacheryPD/git-aliases#11]
Following suit with the `git feature <foo>` alias, it could be handy to also have `git bugfix <foo>` and `git hotfix <foo>` to create `bugfix/foo` and `hotfix/foo` branches respectively. These commands should take in a parameter of which branch to cut from on the remote server (probably execute a fetch first to avoid potential issues). It should also create the branch with the `--no-track` argument so that the tracking will not be set up up front for safety.

**Comment by zach-delong** [comment]
I’m not sure I like the automatic fetching or other options. one of the things that I like about these current aliases is that they are convenience on top of Git, but they don’t hide any Git functionality, so the user still knows basically what command are running. I think by adding fetches we might be making the alias a bit heavy.

However, adding an optional parameter for what branch to cut from is a fantastic idea. I should add that to the feature one.

**Comment by Doug-Murphy** [comment]
I see what you mean. I think having it fetch first is safer, but perhaps not something that should be abstracted out. This should mimic the `git feature` alias.

And yes adding a parameter to `git feature` could be handy indeed.

**Comment by Doug-Murphy** [comment]
Revisiting this, I think this probably isn't worth the time. For work, we already have the cherry picker script to do this for us. I'm not making `bugfix/` or `hotfix/` branches without that anyway. And it's not a _huge_ time saver either. I'm just going to close this. Reopen if you think it's worth doing.
