### ISSUE TITLE
Add alias to delete past X commits

### ISSUE THREAD

**Issue by Doug-Murphy** [ZacheryPD/git-aliases#8]
Sometimes you wind up doing some stuff, and ya really just don't want to keep that. Maybe you resolved conflicts wrong and continued the cherry pick anyway? Maybe you committed on the wrong branch and you need to remove it. Wouldn't it be nice if you could do something like `git dc 1` or `git dc 2` to reset --hard to 1 or 2 (respectively) commits ago? I think it would.

**Comment by zach-delong** [comment]
Is that really that much shorter than git reset —hard HEAD~2 ?

**Comment by Doug-Murphy** [comment]
Yes yes I agree. Best to not pollute the repo with aliases that aren't top tier.
